use crate::setting::config;
use anyhow::{Context, Result};
use console::style;
use serde::{Deserialize, Serialize};
use serde_json::{json, Map, Value};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

/// Contents of a fusion.<env>.json file (flat settings + optional commands).
#[derive(Debug, Serialize, Deserialize)]
pub struct Environment {
    pub env: String,

    /// Commands the project author declares, run by `fusion command <name>`
    #[serde(default)]
    pub commands: BTreeMap<String, String>,

    #[serde(flatten)]
    #[serde(default)]
    extra: BTreeMap<String, Value>,
}

impl Environment {
    /// Settings consumed by Fusion runtime (supports legacy `config` wrapper).
    pub fn settings(&self) -> BTreeMap<String, Value> {
        if let Some(Value::Object(config)) = self.extra.get("config") {
            return config.clone().into_iter().collect();
        }

        self.extra
            .iter()
            .filter(|(key, _)| !matches!(key.as_str(), "config"))
            .map(|(key, value)| (key.clone(), value.clone()))
            .collect()
    }
}

pub fn file_name(env: &str) -> String {
    format!("fusion.{}.json", env)
}

pub fn file_path(project_root: &Path, env: &str) -> PathBuf {
    project_root.join(file_name(env))
}

/// Read the environment file of a project
pub fn read(project_root: &Path, env: &str) -> Result<Environment> {
    let path = file_path(project_root, env);

    let content = fs::read_to_string(&path).with_context(|| {
        format!(
            "Could not read {}. Run `fusion init` first, or pick another environment.",
            path.display()
        )
    })?;

    serde_json::from_str(&content).with_context(|| format!("Could not parse {}", path.display()))
}

fn write_value(target_dir: &Path, env: &str, value: &Value) -> Result<()> {
    let path = file_path(target_dir, env);
    let content = serde_json::to_string_pretty(value)?;

    fs::write(&path, format!("{content}\n"))
        .with_context(|| format!("Could not create {}", path.display()))?;

    println!(
        "{}",
        style(format!("✔ {} created successfully!", path.display()))
            .green()
            .bold()
    );

    Ok(())
}

/// Commands a new project starts with, as an editable example
fn commands(language: &config::Language) -> BTreeMap<String, String> {
    let run = match language {
        config::Language::Python => "python main.py",

        config::Language::TypeScript => "node main.ts",

        config::Language::AspNetCore => "dotnet run",
    };

    BTreeMap::from([("run".to_string(), run.to_string())])
}

fn middleware_config() -> Value {
    let mut map = Map::new();
    map.insert("security".to_string(), json!({
        "enabled": true,
        "hsts": {
            "enabled": false,
            "max_age": 31536000,
            "include_subdomains": true,
            "preload": false
        },
        "content_type_options": "nosniff",
        "frame_options": "DENY",
        "referrer_policy": "strict-origin-when-cross-origin",
        "permissions_policy": "camera=(), microphone=(), geolocation=(), payment=()",
        "coop": "same-origin",
        "corp": "same-origin",
        "csp": null
    }));
    map.insert("cors".to_string(), json!({
        "enabled": false,
        "allow_origins": ["*"],
        "allow_methods": ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"],
        "allow_headers": ["Authorization", "Content-Type", "Accept", "Origin", "X-Request-Id"],
        "expose_headers": ["X-Request-Id"],
        "allow_credentials": false,
        "max_age": 600
    }));
    map.insert("cache".to_string(), json!({
        "enabled": false,
        "default": "no-store"
    }));
    map.insert("request_id".to_string(), json!({
        "enabled": true,
        "header": "X-Request-Id",
        "incoming": true
    }));
    Value::Object(map)
}

fn swagger_config(enabled: bool) -> Value {
    let mut map = Map::new();
    map.insert("enabled".to_string(), json!(enabled));
    map.insert("path".to_string(), Value::String("/swagger".into()));
    map.insert("title".to_string(), Value::String("Fusion API Docs".into()));
    map.insert(
        "info".to_string(),
        json!({
            "title": "Fusion API",
            "version": "1.0.0",
            "description": "API documentation generated by fusion-framework",
            "contact": {
                "name": "API Support",
                "email": "support@example.com"
            },
            "license": {
                "name": "MIT"
            }
        }),
    );
    map.insert(
        "servers".to_string(),
        json!([{ "url": "/", "description": "Current host" }]),
    );
    map.insert(
        "auth".to_string(),
        json!({
            "persistAuthorization": true,
            "schemes": {
                "BearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT"
                },
                "ApiKeyAuth": {
                    "type": "apiKey",
                    "in": "header",
                    "name": "X-API-Key"
                }
            },
            "global": [],
            "oauth": {
                "clientId": "",
                "appName": "Fusion API",
                "scopes": "",
                "usePkceWithAuthorizationCodeGrant": true
            }
        }),
    );
    map.insert(
        "navbar".to_string(),
        json!({
            "enabled": true,
            "showUrlInput": true
        }),
    );
    map.insert(
        "ui".to_string(),
        json!({
            "deepLinking": true,
            "displayOperationId": false,
            "defaultModelsExpandDepth": 1,
            "defaultModelExpandDepth": 1,
            "defaultModelRendering": "example",
            "docExpansion": "list",
            "filter": true,
            "tryItOutEnabled": true,
            "displayRequestDuration": true,
            "showExtensions": false,
            "showCommonExtensions": false,
            "withCredentials": false,
            "syntaxHighlight": {
                "activated": true,
                "theme": "agate"
            }
        }),
    );
    Value::Object(map)
}

fn environment_value(
    env: &str,
    port: u16,
    language: &config::Language,
    host: &str,
    debug: bool,
    swagger_enabled: bool,
) -> Value {
    let mut map = Map::new();
    // Top-level keys are written in this order (requires serde_json preserve_order).
    map.insert("env".to_string(), Value::String(env.to_string()));
    map.insert("host".to_string(), Value::String(host.to_string()));
    map.insert("port".to_string(), json!(port));
    map.insert("debug".to_string(), json!(debug));
    map.insert("reload".to_string(), json!(debug));
    map.insert(
        "templates".to_string(),
        json!({
            "dir": "templates"
        }),
    );
    map.insert(
        "fingerprint".to_string(),
        json!({
            "enabled": debug
        }),
    );
    map.insert(
        "cache".to_string(),
        json!({
            "driver": "moka",
            "max_capacity": 10000,
            "default_ttl": null,
            "connection_string": null,
            "host": "127.0.0.1",
            "port": 6379,
            "username": null,
            "password": null,
            "db": 0
        }),
    );
    map.insert("middleware".to_string(), middleware_config());
    map.insert("swagger".to_string(), swagger_config(swagger_enabled));

    let commands = commands(language);
    if !commands.is_empty() {
        map.insert(
            "commands".to_string(),
            Value::Object(
                commands
                    .into_iter()
                    .map(|(k, v)| (k, Value::String(v)))
                    .collect(),
            ),
        );
    }

    Value::Object(map)
}

fn environment_file(
    target_dir: &Path,
    env: &str,
    port: u16,
    language: &config::Language,
    host: &str,
    debug: bool,
    swagger_enabled: bool,
) -> Result<()> {
    write_value(
        target_dir,
        env,
        &environment_value(env, port, language, host, debug, swagger_enabled),
    )
}

pub fn dev(target_dir: &Path, language: &config::Language) -> Result<()> {
    environment_file(target_dir, "dev", 8080, language, "127.0.0.1", true, true)
}

pub fn prod(target_dir: &Path, language: &config::Language) -> Result<()> {
    environment_file(target_dir, "prod", 9090, language, "0.0.0.0", false, false)
}

pub fn stage(target_dir: &Path, language: &config::Language) -> Result<()> {
    environment_file(target_dir, "stage", 8081, language, "0.0.0.0", false, false)
}

/// Flatten JSON settings into uppercase environment variable names.
pub fn settings_to_env_vars(settings: &BTreeMap<String, Value>) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    flatten_value("", &Value::Object(settings.clone().into_iter().collect()), &mut out);
    out
}

fn flatten_value(prefix: &str, value: &Value, out: &mut BTreeMap<String, String>) {
    match value {
        Value::Object(map) => {
            for (key, nested) in map {
                let next = if prefix.is_empty() {
                    key.to_ascii_uppercase()
                } else {
                    format!("{}_{}", prefix, key.to_ascii_uppercase())
                };
                flatten_value(&next, nested, out);
            }
        }
        Value::Null => {}
        Value::Bool(b) => {
            out.insert(prefix.to_string(), b.to_string());
        }
        Value::Number(n) => {
            out.insert(prefix.to_string(), n.to_string());
        }
        Value::String(s) => {
            out.insert(prefix.to_string(), s.clone());
        }
        Value::Array(items) => {
            out.insert(prefix.to_string(), serde_json::to_string(items).unwrap_or_default());
        }
    }
}

pub fn git(target_dir: &Path, language: &config::Language) -> Result<()> {
    let git_content = match language {
        config::Language::Python => {
            r#"
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[codz]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Environments
.env
.envrc
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Fusion modules vendored by `fusion add`
.fusion/
"#
        }

        config::Language::TypeScript => {
            r#"
# Dependencies
node_modules/

# Build
dist/
*.tsbuildinfo

# Env / secrets
.env
.env.*
!.env.example

# Logs / coverage
logs/
*.log
coverage/
.nyc_output/

# IDE / OS
.idea/
.vscode/
*.swp
.DS_Store

# Fusion modules vendored by `fusion add`
.fusion/
"#
        }

        config::Language::AspNetCore => {
            r#"
# Build
bin/
obj/
out/

# User-specific
*.user
*.suo
.vs/

# Env / secrets
.env
.env.*
!.env.example
appsettings.*.local.json

# IDE / OS
.idea/
.vscode/
.DS_Store

# Fusion modules vendored by `fusion add`
.fusion/
"#
        }
    };

    if !git_content.is_empty() {
        let gitignore_path = target_dir.join(".gitignore");
        fs::write(&gitignore_path, git_content)?;
        println!(
            "{}",
            style(format!(
                "✔ {} created successfully",
                gitignore_path.display()
            ))
            .green()
            .bold()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::setting::config::Language;

    #[test]
    fn test_dev_environment_json_key_order() {
        let dir = std::env::temp_dir().join(format!("fusion-env-order-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        dev(&dir, &Language::Python).unwrap();
        let content = fs::read_to_string(dir.join("fusion.dev.json")).unwrap();

        let env_pos = content.find("\"env\"").unwrap();
        let host_pos = content.find("\"host\"").unwrap();
        let port_pos = content.find("\"port\"").unwrap();
        let debug_pos = content.find("\"debug\"").unwrap();
        let fingerprint_pos = content.find("\"fingerprint\"").unwrap();
        let cache_pos = content.find("\"cache\"").unwrap();
        let middleware_pos = content.find("\"middleware\"").unwrap();
        let swagger_pos = content.find("\"swagger\"").unwrap();
        let commands_pos = content.find("\"commands\"").unwrap();

        assert!(env_pos < host_pos);
        assert!(host_pos < port_pos);
        assert!(port_pos < debug_pos);
        assert!(debug_pos < fingerprint_pos);
        assert!(fingerprint_pos < cache_pos);
        assert!(cache_pos < middleware_pos);
        assert!(middleware_pos < swagger_pos);
        assert!(swagger_pos < commands_pos);

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_dev_environment_includes_fingerprint_middleware_and_swagger() {
        let dir = std::env::temp_dir().join(format!("fusion-env-dev-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        dev(&dir, &Language::Python).unwrap();
        let env = read(&dir, "dev").unwrap();
        let settings = env.settings();
        assert_eq!(env.env, "dev");
        assert_eq!(settings["port"], 8080);
        assert_eq!(settings["reload"], true);
        assert_eq!(settings["templates"]["dir"], "templates");
        assert_eq!(settings["fingerprint"]["enabled"], true);
        assert_eq!(settings["cache"]["driver"], "moka");
        assert_eq!(settings["cache"]["max_capacity"], 10000);
        assert!(settings["cache"]["default_ttl"].is_null());
        assert!(settings["cache"]["connection_string"].is_null());
        assert_eq!(settings["cache"]["host"], "127.0.0.1");
        assert_eq!(settings["cache"]["port"], 6379);
        assert!(settings["cache"]["username"].is_null());
        assert!(settings["cache"]["password"].is_null());
        assert_eq!(settings["cache"]["db"], 0);
        // HTTP cache-headers middleware stays under middleware.cache (separate from app cache).
        assert_eq!(settings["middleware"]["cache"]["enabled"], false);
        assert_eq!(settings["middleware"]["security"]["enabled"], true);
        assert_eq!(settings["swagger"]["enabled"], true);
        assert_eq!(
            env.commands.get("run").map(String::as_str),
            Some("python main.py")
        );

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_stage_port_is_8081() {
        let dir = std::env::temp_dir().join(format!("fusion-env-stage-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        stage(&dir, &Language::TypeScript).unwrap();
        let env = read(&dir, "stage").unwrap();
        let settings = env.settings();
        assert_eq!(settings["port"], 8081);
        assert_eq!(settings["swagger"]["enabled"], false);
        assert_eq!(settings["cache"]["driver"], "moka");
        assert!(settings["cache"]["default_ttl"].is_null());

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_settings_to_env_vars_flattens_nested_keys() {
        let settings = example_settings();
        let vars = settings_to_env_vars(&settings);
        assert_eq!(vars.get("PORT").map(String::as_str), Some("8080"));
        assert_eq!(
            vars.get("MIDDLEWARE_SECURITY_ENABLED").map(String::as_str),
            Some("true")
        );
    }

    fn example_settings() -> BTreeMap<String, Value> {
        let value = environment_value("dev", 8080, &Language::Python, "127.0.0.1", true, true);
        let env: Environment = serde_json::from_value(value).unwrap();
        env.settings()
    }

    #[test]
    fn test_gitignore_written_for_all_languages() {
        for lang in [Language::Python, Language::TypeScript, Language::AspNetCore] {
            let dir = std::env::temp_dir().join(format!(
                "fusion-gitignore-{}-{}",
                lang.name(),
                std::process::id()
            ));
            let _ = fs::remove_dir_all(&dir);
            fs::create_dir_all(&dir).unwrap();
            git(&dir, &lang).unwrap();
            let content = fs::read_to_string(dir.join(".gitignore")).unwrap();
            assert!(content.contains(".fusion/"));
            fs::remove_dir_all(&dir).unwrap();
        }
    }

    #[test]
    fn test_prod_includes_cache_defaults() {
        let dir = std::env::temp_dir().join(format!("fusion-env-prod-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        prod(&dir, &Language::AspNetCore).unwrap();
        let env = read(&dir, "prod").unwrap();
        let settings = env.settings();
        assert_eq!(settings["port"], 9090);
        assert_eq!(settings["cache"]["driver"], "moka");
        assert!(settings["cache"]["default_ttl"].is_null());
        assert_eq!(settings["cache"]["host"], "127.0.0.1");
        assert_eq!(settings["cache"]["port"], 6379);
        assert!(settings["cache"]["password"].is_null());

        fs::remove_dir_all(&dir).unwrap();
    }
}
