use crate::setting::config;
use anyhow::{Context, Result};
use console::style;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use uuid::Uuid;



/// generate uuid only fot environments
fn generate_uuid() -> String {
    let id = Uuid::new_v4();
    format!("fusion-framework-{id}")
}


/// Contents of a fusion.<env>.json file
#[derive(Debug, Serialize, Deserialize)]
pub struct Environment {
    pub env: String,

    pub config: serde_json::Value,

    /// Commands the project author declares, run by `fusion command <name>`
    #[serde(default)]
    pub commands: BTreeMap<String, String>,
}

pub fn file_name(env: &str) -> String {
    format!("fusion.{}.json", env)
}

pub fn file_path(project_root: &Path, env: &str) -> PathBuf {
    project_root.join(file_name(env))
}

/// Read the environment file of a project
pub fn read(project_root: &Path, env: &str) -> Result<Environment> {
    let path = file_path(project_root, env);

    let content = fs::read_to_string(&path).with_context(|| {
        format!(
            "Could not read {}. Run `fusion init` first, or pick another environment.",
            path.display()
        )
    })?;

    serde_json::from_str(&content).with_context(|| format!("Could not parse {}", path.display()))
}

fn write(target_dir: &Path, environment: &Environment) -> Result<()> {
    let path = file_path(target_dir, &environment.env);

    let content = serde_json::to_string_pretty(environment)?;

    fs::write(&path, format!("{}\n", content))
        .with_context(|| format!("Could not create {}", path.display()))?;

    println!(
        "{}",
        style(format!("✔ {} created successfully!", path.display()))
            .green()
            .bold()
    );

    Ok(())
}

/// Commands a new project starts with, as an editable example
fn commands(language: &config::Language) -> BTreeMap<String, String> {
    let run = match language {
        config::Language::Python => "python main.py",

        config::Language::TypeScript => "npx tsx main.ts",

        config::Language::AspNetCore => "dotnet run",
    };

    BTreeMap::from([("run".to_string(), run.to_string())])
}

fn swagger_config(enabled: bool) -> serde_json::Value {
    json!({
        "enabled": enabled,
        "path": "/swagger",
        "title": "Fusion API Docs",
        "info": {
            "title": "Fusion API",
            "version": "1.0.0",
            "description": "API documentation generated by fusion-framework",
            "contact": {
                "name": "API Support",
                "email": "support@example.com"
            },
            "license": {
                "name": "MIT"
            }
        },
        "servers": [
            { "url": "/", "description": "Current host" }
        ],
        "auth": {
            "persistAuthorization": true,
            "schemes": {
                "BearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT"
                },
                "ApiKeyAuth": {
                    "type": "apiKey",
                    "in": "header",
                    "name": "X-API-Key"
                }
            },
            "global": [],
            "oauth": {
                "clientId": "",
                "appName": "Fusion API",
                "scopes": "",
                "usePkceWithAuthorizationCodeGrant": true
            }
        },
        "navbar": {
            "enabled": true,
            "showUrlInput": false
        },
        "ui": {
            "deepLinking": true,
            "displayOperationId": false,
            "defaultModelsExpandDepth": 1,
            "defaultModelExpandDepth": 1,
            "defaultModelRendering": "example",
            "docExpansion": "list",
            "filter": true,
            "tryItOutEnabled": true,
            "displayRequestDuration": true,
            "showExtensions": false,
            "showCommonExtensions": false,
            "withCredentials": false,
            "syntaxHighlight": {
                "activated": true,
                "theme": "agate"
            }
        }
    })
}

fn environment_file(
    target_dir: &Path,
    env: &str,
    port: u16,
    secret_key: &str,
    language: &config::Language,
    host: &str,
    debug: bool,
    swagger_enabled: bool,
) -> Result<()> {
    write(
        target_dir,
        &Environment {
            env: env.to_string(),
            config: json!({
                "port": port,
                "secret_key": secret_key,
                "host": host,
                "debug": debug,
                "fingerprint": {
                    "enabled": true
                },
                "swagger": swagger_config(swagger_enabled),
            }),
            commands: commands(language),
        },
    )
}

pub fn dev(target_dir: &Path, language: &config::Language) -> Result<()> {
    // Explicit port — do not rely on fusion-core's bare default (3000).
    environment_file(target_dir, "dev", 8080, &generate_uuid(), language, "127.0.0.1", true, true)
}

pub fn prod(target_dir: &Path, language: &config::Language) -> Result<()> {
    environment_file(target_dir, "prod", 9090, &generate_uuid(), language, "HOST", false, false)
}

pub fn stage(target_dir: &Path, language: &config::Language) -> Result<()> {
    environment_file(target_dir, "stage", 8081, &generate_uuid(), language, "HOST", false, false)
}

pub fn git(target_dir: &Path, language: &config::Language) -> Result<()> {
    let git_content = match language {
        config::Language::Python => {
            r#"
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[codz]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Environments
.env
.envrc
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Fusion modules vendored by `fusion add`
.fusion/
"#
        }

        config::Language::TypeScript => {
            r#"
# Dependencies
node_modules/

# Build
dist/
*.tsbuildinfo

# Env / secrets
.env
.env.*
!.env.example

# Logs / coverage
logs/
*.log
coverage/
.nyc_output/

# IDE / OS
.idea/
.vscode/
*.swp
.DS_Store

# Fusion modules vendored by `fusion add`
.fusion/
"#
        }

        config::Language::AspNetCore => {
            r#"
# Build
bin/
obj/
out/

# User-specific
*.user
*.suo
.vs/

# Env / secrets
.env
.env.*
!.env.example
appsettings.*.local.json

# IDE / OS
.idea/
.vscode/
.DS_Store

# Fusion modules vendored by `fusion add`
.fusion/
"#
        }
    };

    if !git_content.is_empty() {
        let gitignore_path = target_dir.join(".gitignore");
        fs::write(&gitignore_path, git_content)?;
        println!(
            "{}",
            style(format!(
                "✔ {} created successfully",
                gitignore_path.display()
            ))
            .green()
            .bold()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::setting::config::Language;

    #[test]
    fn test_dev_environment_includes_fingerprint_and_swagger() {
        let dir = std::env::temp_dir().join(format!("fusion-env-dev-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        dev(&dir, &Language::Python).unwrap();
        let env = read(&dir, "dev").unwrap();
        assert_eq!(env.env, "dev");
        assert_eq!(env.config["port"], 8080);
        assert_eq!(env.config["fingerprint"]["enabled"], true);
        assert_eq!(env.config["swagger"]["enabled"], true);
        assert_eq!(
            env.commands.get("run").map(String::as_str),
            Some("python main.py")
        );

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_stage_port_is_8081() {
        let dir = std::env::temp_dir().join(format!("fusion-env-stage-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        stage(&dir, &Language::TypeScript).unwrap();
        let env = read(&dir, "stage").unwrap();
        assert_eq!(env.config["port"], 8081);
        assert_eq!(env.config["swagger"]["enabled"], false);

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_gitignore_written_for_all_languages() {
        for lang in [Language::Python, Language::TypeScript, Language::AspNetCore] {
            let dir = std::env::temp_dir().join(format!(
                "fusion-gitignore-{}-{}",
                lang.name(),
                std::process::id()
            ));
            let _ = fs::remove_dir_all(&dir);
            fs::create_dir_all(&dir).unwrap();
            git(&dir, &lang).unwrap();
            let content = fs::read_to_string(dir.join(".gitignore")).unwrap();
            assert!(content.contains(".fusion/"));
            fs::remove_dir_all(&dir).unwrap();
        }
    }
}
