use crate::setting::config;
use anyhow::{Context, Result};
use console::style;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use uuid::Uuid;



/// generate uuid only fot environments
fn generate_uuid() -> String {
    let id = Uuid::new_v4();
    format!("fusion-framework-{id}")
}


/// Contents of a fusion.<env>.json file
#[derive(Debug, Serialize, Deserialize)]
pub struct Environment {
    pub env: String,

    pub config: serde_json::Value,

    /// Commands the project author declares, run by `fusion command <name>`
    #[serde(default)]
    pub commands: BTreeMap<String, String>,
}

pub fn file_name(env: &str) -> String {
    format!("fusion.{}.json", env)
}

pub fn file_path(project_root: &Path, env: &str) -> PathBuf {
    project_root.join(file_name(env))
}

/// Read the environment file of a project
pub fn read(project_root: &Path, env: &str) -> Result<Environment> {
    let path = file_path(project_root, env);

    let content = fs::read_to_string(&path).with_context(|| {
        format!(
            "Could not read {}. Run `fusion init` first, or pick another environment.",
            path.display()
        )
    })?;

    serde_json::from_str(&content).with_context(|| format!("Could not parse {}", path.display()))
}

fn write(target_dir: &Path, environment: &Environment) -> Result<()> {
    let path = file_path(target_dir, &environment.env);

    let content = serde_json::to_string_pretty(environment)?;

    fs::write(&path, format!("{}\n", content))
        .with_context(|| format!("Could not create {}", path.display()))?;

    println!(
        "{}",
        style(format!("✔ {} created successfully!", path.display()))
            .green()
            .bold()
    );

    Ok(())
}

/// Commands a new project starts with, as an editable example
fn commands(language: &config::Language) -> BTreeMap<String, String> {
    let run = match language {
        config::Language::Python => "python main.py",

        config::Language::TypeScript => "npx tsx main.ts",

        config::Language::AspNetCore => "dotnet run",
    };

    BTreeMap::from([("run".to_string(), run.to_string())])
}

fn swagger_config(enabled: bool) -> serde_json::Value {
    json!({
        "enabled": enabled,
        "path": "/swagger",
        "title": "Fusion API Docs",
        "info": {
            "title": "Fusion API",
            "version": "1.0.0",
            "description": "API documentation generated by fusion-framework",
            "contact": {
                "name": "API Support",
                "email": "support@example.com"
            },
            "license": {
                "name": "MIT"
            }
        },
        "servers": [
            { "url": "/", "description": "Current host" }
        ],
        "auth": {
            "persistAuthorization": true,
            "schemes": {
                "BearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT"
                },
                "ApiKeyAuth": {
                    "type": "apiKey",
                    "in": "header",
                    "name": "X-API-Key"
                }
            },
            "global": [],
            "oauth": {
                "clientId": "",
                "appName": "Fusion API",
                "scopes": "",
                "usePkceWithAuthorizationCodeGrant": true
            }
        },
        "navbar": {
            "enabled": true,
            "showUrlInput": true
        },
        "ui": {
            "deepLinking": true,
            "displayOperationId": false,
            "defaultModelsExpandDepth": 1,
            "defaultModelExpandDepth": 1,
            "defaultModelRendering": "example",
            "docExpansion": "list",
            "filter": true,
            "tryItOutEnabled": true,
            "displayRequestDuration": true,
            "showExtensions": false,
            "showCommonExtensions": false,
            "withCredentials": false,
            "syntaxHighlight": {
                "activated": true,
                "theme": "agate"
            }
        }
    })
}

fn environment_file(
    target_dir: &Path,
    env: &str,
    port: u16,
    secret_key: &str,
    language: &config::Language,
    host: &str,
    debug: bool,
    swagger_enabled: bool,
) -> Result<()> {
    write(
        target_dir,
        &Environment {
            env: env.to_string(),
            config: json!({
                "port": port,
                "secret_key": secret_key,
                "host": host,
                "debug": debug,
                "swagger": swagger_config(swagger_enabled),
            }),
            commands: commands(language),
        },
    )
}

pub fn dev(target_dir: &Path, language: &config::Language) -> Result<()> {
    environment_file(target_dir, "dev", 8080, &generate_uuid(), language, "127.0.0.1", true, true)
}

pub fn prod(target_dir: &Path, language: &config::Language) -> Result<()> {
    environment_file(target_dir, "prod", 9090, &generate_uuid(), language, "HOST", false, false)
}

pub fn stage(target_dir: &Path, language: &config::Language) -> Result<()> {
    environment_file(target_dir, "stage", 1010, &generate_uuid(), language, "HOST", false, false)
}

pub fn git(target_dir: &Path, language: &config::Language) -> Result<()> {
    let git_content = match language {
        config::Language::Python => {
            r#"
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[codz]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Environments
.env
.envrc
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# mypy
.mypy_cache/
.dmypy.json
dmypy.json"#
        }

        config::Language::TypeScript => {
            r#"
node_modules/
.node_modules/
built/*
tests/cases/rwc/*
tests/cases/perf/*
!tests/cases/webharness/compilerToString.js
test-args.txt
~*.docx
\#*\#
.\#*
tests/baselines/local/*
tests/baselines/local.old/*
tests/services/baselines/local/*
tests/baselines/local.old/*
tests/baselines/reference/*
tests/baselines/reference/projectOutput/*
tests/baselines/local/projectOutput/*
tests/baselines/reference/testresults.tap
tests/baselines/symlinks/*
tests/services/baselines/prototyping/local/*
tests/services/browser/typescriptServices.js
src/harness/*.js
src/compiler/diagnosticInformationMap.generated.ts
src/compiler/diagnosticMessages.generated.json
src/parser/diagnosticInformationMap.generated.ts
src/parser/diagnosticMessages.generated.json
rwc-report.html
*.swp
build.json
*.actual
tests/webTestServer.js
tests/webTestServer.js.map
tests/webhost/*.d.ts
tests/webhost/webtsc.js
tests/cases/**/*.js
tests/cases/**/*.js.map
*.config
scripts/eslint/built/
scripts/debug.bat
scripts/run.bat
scripts/**/*.js
scripts/**/*.js.map
coverage/
internal/
**/.DS_Store
.settings
**/.vs
**/.vscode/*
!**/.vscode/tasks.json
!**/.vscode/settings.template.json
!**/.vscode/launch.template.json
!**/.vscode/extensions.json
!tests/cases/projects/projectOption/**/node_modules
!tests/cases/projects/NodeModulesSearch/**/*
!tests/baselines/reference/project/nodeModules*/**/*
.idea
yarn.lock
yarn-error.log
.parallelperf.*
tests/baselines/reference/dt
.failed-tests
TEST-results.xml
package-lock.json
.eslintcache
*v8.log
/lib/"#
        }

        config::Language::AspNetCore => "",
    };

    if !git_content.is_empty() {
        let gitignore_path = target_dir.join(".gitignore");
        fs::write(&gitignore_path, git_content)?;
        println!(
            "{}",
            style(format!(
                "✔ {} created successfully",
                gitignore_path.display()
            ))
            .green()
            .bold()
        );
    }
    Ok(())
}
